### ISSUE TITLE
Access to connection methods (sendDigits, etc)

### ISSUE THREAD

**Issue by Pagebakers** [rogchap/react-native-twilio#10]
Is there any way to get access to the connection object?

Ideally the API would be the same as the original Twilio libraries.
Which means returning the connection instance from Twilio.connect() and in the onIncoming event handler.

**Comment by rogchap** [comment]
Yup, this method is currently missing. Seems an easy addition to add though. 
Feel free to send a PR. 👍

**Comment by Pagebakers** [comment]
This is actually the first time I worked with the react native internals, I exported the sendDigits method. 

I wasn't sure how to export the connection object, but I guess this is sufficient for now :)
