### ISSUE TITLE
App crashes on connect()

### ISSUE THREAD

**Issue by robbiemoore** [rogchap/react-native-twilio#15]
Hey guys, when I call Twilio.connect({To: '+447842111281'}); the app crashes. Can someone please give an example of how to write a simple dail app using this for ios?

**Comment by jigyasam** [comment]
@robbiemoore Did you ever manage to resolve this? The app crashes on `connect` for me too, but the phone rings.

**Comment by naviocean** [comment]
same issue.

**Comment by robbiemoore** [comment]
Hey, I resorted to using VoxImplant. The react-native integration works really well.
