### ISSUE TITLE
Linker error: libRCTTwilio.a does not contain bitcode

### ISSUE THREAD

**Issue by EricWithCare** [rogchap/react-native-twilio#4]
I'm using your library for my iOS app, I've followed your instructions to add the library project to the app project. I've been able to run it in 'Debug' on the simulator, but when I try to compile it for 'Release', I get this following linker error.

`ld: '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fjuggfxrdihhjtbxzjccuzpnorpk/Build/Products/Release-iphoneos/libRCTTwilio.a(a_int.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Note: sometimes it says architecture arm64, sometimes it says armv

I've checked that the 'Enable Bitcode' build setting is set to 'yes' on both the app project level and app target level. I've also tried adding `-fembed-bitcode` and `-fembed-bitcode-marker` to the LLVM Custom Compiler Flags: Other C Flags/Other C++ Flags, but I get the same error. Any help would be appreciated thanks.

**Comment by rogchap** [comment]
You need to set `Enable Bitcode` to `NO` for your target application.
If this does not solve your problem please re-open.

**Comment by EricWithCare** [comment]
I tried setting `Enable`Bitcode` to NO and the build does successfully archive, but the resulting archive appears under Other Items as a "Generic Xcode Archive" rather than an iOS App Archive. I also can't Upload to the App Store. I'm not sure why. Having said that though, the Twilio project does have Bitcode enabled so shouldn't the App be able to build with it on
